spring:
  #  config:
  #    import: optional:file:.env[]
  application:
    name: todo-chats-bot
  #db  related settings
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_chats
    username: experiment001
    password: experiment001
    driver-class-name: org.postgresql.Driver



bot:
  name: "todo_chat_bot"
  token: 7080397291:AAHMvSwrsERzGPa-W7zsQd5cDOw04LqsJFM
  owner: 426857196

cron:
  scheduler: "0 * * * * *"
